services:
  agent.izdrail.com:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWUSER: '${WWWUSER:-1000}'
        WWWGROUP: '${WWWGROUP:-1001}'
    image: izdrail/agent.izdrail.com
    container_name: agent.izdrail.com
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - '/app/node_modules'
      - '/app/.next'
    networks:
      - sail
networks:
  sail:
    driver: bridge
